<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class myValidator extends FormRequest{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize(){
        return false;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules(){
        return [
            'name'=>'required',
            'age'=>'required',
            'score'=>'required'
        ];
    }

    public function messages(){

//        return parent::messages(); // TODO: Change the autogenerated stub
        return [
//            'title.required' => 'A title is required',
            'name.required' => 'name属性必填',
            'age.reauired' =>'age属性必填',
            'email required'=>'emial格式不正确'
        ];
    }
}
